### ISSUE TITLE
project directory structure

### ISSUE THREAD

**Issue by behollister** [agdturner/ccg-v2d#1]
Pertaining to JOSS review [comment](https://github.com/openjournals/joss-reviews/issues/4283#issuecomment-1116416765). Please reduce depth of project directory structure from top-level directory of git repository. 

For instance: ccg-v3d\src\test\java\uk\ac\leeds\ccg\v3d

This is the test files directory, separate from the library source (also along similar path but under main/). 

Best to create an Eclipse project for streamlined code inspection and test framework execution of provided tests.

Example for possible file layout (Eclipse project and source tree):

![Screenshot (248)](https://user-images.githubusercontent.com/20388050/166518458-cef5a273-db2c-463a-9c40-2973950ab6c0.png)

**Comment by agdturner** [comment]
I use NetBeans. Why is the path length an issue?

**Comment by agdturner** [comment]
Are you opening as a Maven project in Eclipse?

**Comment by agdturner** [comment]
It is good practice to have the test files separate and in the same structure as the src. I could shorten the path, but I don't see why this is necessary.

**Comment by behollister** [comment]
Please provide info in the README, as there is only a reference to the POM xml itself. This makes use of the project potentially unclear, especially for those not familiar with Maven, etc.

The README could provide simple cookbook instructions on compilation and running unit tests, for at least one particular dev tool. Did I perhaps miss this, such as additional user info available through external (website) documentation?

Also, a link to the official docs for Maven would be nice too, that is:

https://maven.apache.org/pom.html#What_is_the_POM

**Comment by agdturner** [comment]
Why are you reviewing the 2D Vector Library which is immature in comparison to the 3D Vector Library. I have updated the ccg-v3d README to provide some guidance of how to get set up and running using Maven (https://github.com/agdturner/ccg-v3d/blob/master/README.md). HTH

**Comment by behollister** [comment]
As part of the review, if the 2D library is included in the submission, then all code needs to be tested. If you believe there is still "immature" code in the repository submission, however, it may be best left out.

**Comment by agdturner** [comment]
Hi Brad, Sorry for the confusion, but the library submitted to JOSS is ccg-v3d. This comment thread is for some reason in the ccg-v2d repository. The ccg-v2d library is not part of what is under review for JOSS. Best wishes, Andy

**Comment by behollister** [comment]
Actually, I'm sorry about this. I should have placed the issue in ccg-v3d instead. I'll look into migrating the comment thread, but I don't believe that's possible. Will have to close this and link from ccg-v3d.

Sorry for any confusion.

**Comment by behollister** [comment]
Comments related to ccg-v2d, but were intended for ccg-v3d.
